### ISSUE TITLE
[ADD STORY]

### ISSUE THREAD

**Issue by VedasreeM** [SreejithMVarma/Failurestories#5]
## Author: Vedasree M

   ![Vedasree M](https://github.com/SreejithMVarma/Failurestories/assets/126886440/090aa2b4-7c06-4624-8c73-d1cd655faeeb)

---

Yeah! Story!!! Of course….there is. Is it a fiction or real life? And the answer is hidden….!!

Girl! Yeah there was a girl. She was just unique in her way. What made her unique was she always think about others and care all people without thinking a little about her! She always helps people come to her. That was her good quality and also her biggest weakness! What to do? That was the way she is. She was very good in her academics as well as extra-curricular activities in her school. But the problem that she has always was she feels loneliness in every moment of her life. Do you think she’s an introvert now? Nah…….she’s not. Even though she can solve the problems, calculations that seen on textbooks, but she never able to find the solution of this problem. Why? Why? Why? This question orbits over her head all over the time. She even cries countless times a day because of this. But no one can see it. That’s the girl hidden in her! Sometimes (most of the times) her pillow would dive like a fish dive in a sea….Laughing??? U can laugh. But that was her condition.

In everyone’s life, there would be definitely a best friend or close friend (word varies with people) in their life whom they can share every minute things happened to their life and have the license to talk anything anytime no matter what it is. As everyone says like a cliché “ It is really a blessing to have someone who makes your life easier and brings you happiness, whether they’re friend or family member or anyone.” But for her it remains a dream! Sometimes she feels somebody as her best friend and she tries to share her thoughts and feelings of her. But when she knows that he/she’s no more her best friend and they all are acting like a friend for their needs, it was just like dying. Her condition at that time cannot express by words. It is just like as good as dead! Every friend came to her life for their needs and they leaves her after making her torned piece of heart again torn! Anyway she doesn’t need anyone’s sympathy. Truly she’s an innocent girl…right??

She is dark in colour. So what? Yes, there’s something hidden in it. Yeah, everyone teasing her or somewhat annoying her because of her colour. Even small children to elder ones teasing her by saying that “You’re black”..etc….Her innocent sweet heart pains even if it was a joke.

She thinks she can solve all her problems in her life if she gets a best friend in her journey. But she didn’t got it till now (I’m writing). Still she loves everyone unconditionally! She didn’t have any angry to anyone. And she always tells to her in all her bad times that “I’m OK”. She is livin’ with that Manthra. That’s SHE!

I’m sooooo wondered that …’is there is any girl like her in this Era!’ Oh what a surprise!

Her STORY doesn’t ends here. Her journey continues till she gets a best friend as she expects!

I don’t know is it a story or not….I just scribbled down the thoughts that came to mind in my simple language : )

---

[Connect with me on GitHub: [VedasreeM](https://github.com/VedasreeM)]

**Comment by DanielZhang111** [comment]
Wait, for this to be counted for hacktoberfest, we just write a story?

**Comment by SreejithMVarma** [comment]
> Wait, for this to be counted for hacktoberfest, we just write a story?

We believe sharing a real personal experience is worth the same as other code contributions! 
Try it out!!

Thank You!
